# numpy basics


In [50]:
#IMPORTING NUMPY

import numpy as np


In [6]:
a=np.array([1,2,3])
print(a)

[1 2 3]


In [7]:
b=np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [9]:
# getting dimension info
a.ndim


1

In [10]:
b.ndim


2

In [11]:
b.shape


(2, 3)

In [12]:
#data type
a.dtype

dtype('int32')

In [13]:
a.itemsize

4

In [14]:
b.itemsize

8

In [15]:
#total size
a.size*a.itemsize

12

In [16]:
a.nbytes

12

In [18]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [19]:
#get a specific element[r,c]
a[1,5]

13

In [20]:
#GET A SPECIFIC ROW
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [24]:
#GET A SPECIFIC column
a[:,2:4]

array([[ 3,  4],
       [10, 11]])

In [25]:
#[startindex:endindex:stepsize]
a[0,1:-1:2]

array([2, 4, 6])

In [32]:
a[:,:4]

array([[ 1,  2,  3,  4],
       [ 8,  9, 10, 11]])

In [33]:
a[1,5]=20 #easy to change

In [34]:
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [35]:
a[:,2]=[1,2]

In [36]:
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [37]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
#to get element in 3d work OUTSIDE IN [Z.ROW,COLUMN]
b[0,1,1]

4

In [39]:
#replace
b[:,1,:]=[[9,9],[8,8]]

In [40]:
print(b)

[[[1 2]
  [9 9]]

 [[5 6]
  [8 8]]]


In [41]:
#INITIALIZING DIFFERENT TYPES OF ARRAYS

#ALL ZEROES
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [42]:
np.zeros((2,3,4)) #3d

array([[[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]],

       [[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]]])

In [43]:
#all 1s matrix
np.ones((4,2,2),dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [44]:
#anyother number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [46]:
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [47]:
#random decimal arrays
np.random.rand(4,2)

array([[0.99477685, 0.07441228],
       [0.48835482, 0.5468669 ],
       [0.78004313, 0.74975165],
       [0.32669168, 0.3344537 ]])

In [48]:
np.random.rand(4,2,3)

array([[[0.48415346, 0.7562207 , 0.21290485],
        [0.37851624, 0.18053754, 0.39484881]],

       [[0.47972024, 0.91483556, 0.37736801],
        [0.18137725, 0.96806836, 0.52727472]],

       [[0.13246951, 0.82306507, 0.22622544],
        [0.67748707, 0.19012463, 0.51976772]],

       [[0.39456566, 0.31183786, 0.03281386],
        [0.35626442, 0.03641591, 0.0409695 ]]])

In [51]:
#random integer values
np.random.randint(4,7,size=(3,3)) #number between 4-7

array([[4, 6, 4],
       [4, 6, 6],
       [5, 6, 4]])

In [52]:
np.identity(5) #identity matrix

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [56]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [60]:
c=np.ones((5,5))
print(c)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [62]:
c[1:-1,1:-1]=0

In [63]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [64]:
c[2,2]=9

In [65]:
print(c)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [68]:
##be careful when copying arrays

In [67]:
#if we change value in copied array it cahnges value of both
#so use copy function , dont simply do =

a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)

[100   2   3]


# MATHEMATICS##


In [27]:
a= np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [5]:
a*2

array([2, 4, 6, 8])

In [8]:
a=+2
print(a)

2


In [9]:
a= np.array([1,2,3,4])


In [10]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [11]:
b=np.array([1,0,1,0])

In [12]:
a+b

array([2, 2, 4, 4])

In [13]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [14]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [15]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [16]:
print(a)

[1 2 3 4]


# Linear Algebra - 


In [28]:
#matrix multiply
a= np.ones((2,3))
print(a)

b= np.full((3,2),2)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


In [18]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [19]:
#determinant
c=np.identity(3)
np.linalg.det(c)

1.0

# Statistics



In [29]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [21]:
np.min(stats)

1

In [25]:
np.max(stats)

6

In [26]:
np.sum(stats,axis=0)

array([5, 7, 9])

# Reorganizing arrays


In [30]:
before = np.array([[1,2,3,4],[5,6,7,8]])

In [36]:
after = before.reshape((1,8))
print(after)

[[1 2 3 4 5 6 7 8]]


In [37]:
after = before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [38]:
after = before.reshape((8,1))
print(after)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [40]:
#Vertical stacking vectors

v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack((v1,v2))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [41]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# SOME MORE THINGSSS

In [47]:
filedata = np.genfromtxt('F:\sample.txt',delimiter=',')
filedata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [48]:
filedata = np.genfromtxt('F:\sample.txt',delimiter=',')
filedata.astype('int32')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [49]:
filedata

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

# Boolean Masking and Advance Indexing

In [51]:
filedata>4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [52]:
filedata>40

array([False, False, False, False, False, False, False, False, False,
       False])

In [54]:
filedata[filedata>5]

array([ 6.,  7.,  8.,  9., 10.])

In [55]:
##INDEX WITH A LIST IN NumPY
a=np.array([1,2,3,4,5,6,7,8,9,10])
a[[1,2,8]]

array([2, 3, 9])

In [58]:
np.any(filedata>5,axis=0)

True

In [59]:
np.all(filedata>5,axis=0)

False

In [61]:
((filedata >5) & (filedata<8))

array([False, False, False, False, False,  True,  True, False, False,
       False])